project_id = "dtxbrnrpzepwoxooqwlj"

[functions.create-checkout]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false

[functions.send-email]
verify_jwt = false

[functions.send-password-reset]
verify_jwt = false

[functions.auto-password-reset]
verify_jwt = false